HELP_CONTENT = [
    {
        "id": "quick_start",
        "title": "快速上手",
        "items": [
            {
                "id": "output_cheatsheet",
                "title": "输出速查",
                "tldr": "不确定会产出啥？去勾选help旁边的“输出预览”（或“输出速查（动态）”点刷新），它会按你当前勾选列出证据清单。",
                "steps": [
                    "打开 Help → 选择“输出速查（动态）”页。",
                    "点击【刷新】根据当前勾选实时更新列表。",
                    "按列表里的路径去找图/表，直接当作证据链目录。",
                ],
                "use_when": "想确认跑完会得到哪些图/表/日志。",
                "inputs": ["无额外输入，跟随当前勾选状态"],
                "actions": ["Help 页签 → 输出速查（动态） → 刷新"],
                "outputs": ["动态列表（不生成新文件，仅列出预计文件）"],
                "insights": "提前知道证据链，避免漏跑或漏存。",
            },
            {
                "id": "qs_roi",
                "title": "ROI 一眼流（推荐）",
                "tldr": "最少输入，最快得到 ROI 接触+电势对比图。",
                "steps": [
                    "模式=研究；预设=只要ROI（推荐）",
                    "填：链ID + ROI残基表达式",
                    "点：生成 .cxc → ChimeraX runscript",
                ],
                "use_when": "需要用最短路径拿到局部接触+电势的对比图。",
                "inputs": ["链 ID（默认 A）", "ROI 残基表达式（如 283,286,291,298-300）"],
                "actions": ["研究模式 → 勾 ROI 接触 + ROI 静电势", "生成 .cxc → 在 ChimeraX 执行 runscript"],
                "outputs": [
                    "out_dir/gate_sites/WT_sites_contacts.png",
                    "out_dir/gate_sites/WT_sites_coulombic.png",
                    "out_dir/gate_sites/<MUT>_sites_contacts.png",
                    "out_dir/gate_sites/<MUT>_sites_coulombic.png",
                ],
                "insights": "两张图就能交代局部接触+电势的倾向变化，适合直接写进 stage3 的 Patch_Electrostatics 和 Contacts_Qualitative。",
                "pitfalls": ["链 ID 写错=全空", "ROI 表达式写错=输出为空"],
            },
        ],
    },
    {
        "id": "env_setup",
        "title": "环境配置｜HOLE & MSA（必看）",
        "items": [
            {
                "id": "env_self_check",
                "title": "一键自检：你电脑到底缺啥",
                "tldr": "先别急着点“运行 HOLE / 一键 MSA”，先确认 WSL、Clustal-Omega、conda、HOLE 都“活着”。（因为程序本质是：Windows 调 wsl bash -lc ... 去跑命令）",
                "steps": [
                    "打开 Windows 终端：输入 wsl，看能不能进 Ubuntu。",
                    "在 Ubuntu 里跑：clustalo --version（MSA 用它）。",
                    "在 Ubuntu 里跑：hole（HOLE 用它；至少要能输出帮助/版本信息）。",
                ],
                "use_when": "第一次使用 Help，或准备运行 HOLE/MSA 前。",
                "inputs": ["WSL Ubuntu 可用", "clustalo 可执行", "hole 可执行"],
                "actions": ["Windows 终端进入 WSL", "执行 clustalo/hole 自检命令"],
                "outputs": ["命令能输出版本/帮助信息"],
                "insights": "先确认底层命令可跑，再去点 GUI 按钮，避免“先撞墙再看 FAQ”。",
                "pitfalls": ["WSL 未安装或未启动", "clustalo/hole 未安装或路径不对"],
            },
            {
                "id": "env_wsl_why",
                "title": "WSL：为什么必须装它",
                "tldr": "本程序的 HOLE/MSA 不是在 Windows 原生跑，而是让 Windows 去叫 WSL 跑命令。",
                "steps": [
                    "安装并启动 Ubuntu（WSL2）。",
                    "确认 Windows 盘能在 WSL 里看到：比如 D: 对应 /mnt/d（程序会把 Windows 路径转成 /mnt/...）。",
                    "记住一个铁律：HOLE 工作目录最好放在 D/E 盘普通英文路径（别带奇怪符号、别太深）。",
                ],
                "use_when": "准备开始配置 HOLE/MSA 之前。",
                "inputs": ["已安装 WSL2 + Ubuntu"],
                "actions": ["WSL 里检查 /mnt 下的 Windows 盘"],
                "outputs": ["WSL 能访问 Windows 路径"],
                "insights": "路径可达=后续 HOLE/MSA 能顺利执行。",
            },
            {
                "id": "env_hole_conda",
                "title": "HOLE 自动模式：conda 只需要改一次",
                "tldr": "HOLE 自动运行时，程序会在 WSL 里执行：. <conda.sh> && conda activate <env> && hole < inp > log",
                "steps": [
                    "在 WSL 跑 conda info --base，拿到 base 路径。",
                    "把 PP.py 里 HOLE_WSL_CONDA_INIT 改成 <base>/etc/profile.d/conda.sh。",
                    "把 HOLE_WSL_CONDA_ENV 改成你装 HOLE 的环境名（例如 hole_env）。",
                ],
                "use_when": "HOLE 自动运行失败或首次配置 HOLE。",
                "inputs": ["WSL 中可用 conda", "HOLE 已安装在某个环境"],
                "actions": ["查询 conda base 路径", "更新 PP.py 配置"],
                "outputs": ["HOLE 自动调用可用"],
                "insights": "这一步讲清楚，用户就不会在“HOLE 自动运行失败”里盲修。",
            },
            {
                "id": "env_msa_clustalo",
                "title": "MSA：Clustal-Omega 的路径怎么配",
                "tldr": "MSA 的“一键跑”会让 Windows 执行：wsl bash -lc 'cd /mnt/... && /usr/bin/clustalo -i xxx.fasta -o xxx_msa.aln ...'",
                "steps": [
                    "在 WSL 装好 clustalo，并确认 clustalo --version 能跑。",
                    "PP.py 里确认 CLUSTALO_WSL_EXE=\"/usr/bin/clustalo\"（换机器就改这里）。",
                    "如果报 “找不到 Clustal-Omega”，优先检查这个路径，再看 WSL 是否可用。",
                ],
                "use_when": "MSA 一键运行失败或首次配置 clustalo。",
                "inputs": ["WSL 中可用 clustalo"],
                "actions": ["检查 clustalo 路径", "更新 PP.py 配置"],
                "outputs": ["MSA 一键运行正常"],
                "insights": "路径配好一次即可复用。",
            },
        ],
    },
    {
        "id": "hole_pipeline_guide",
        "title": "HOLE 管道｜从 0 到曲线",
        "items": [
            {
                "id": "hole_short_loop",
                "title": "HOLE 最短闭环（推荐）",
                "tldr": "你只需要准备 WT+突变体 PDB，剩下 GUI 帮你把文件名统一、写 inp、跑 WSL、再从 log 里扒出曲线和指标。",
                "steps": [
                    "在 HOLE 区：点 “从 WT+突变体准备 HOLE PDB”（会复制成 <模型名>.pdb）。",
                    "填 cpoint/cvect/sample/endrad/radius（或先用“自动推荐 cpoint/cvect”那套）。",
                    "勾 “自动在 WSL 中调用 HOLE” + “根据 *_hole.log 生成 CSV & 曲线图”，然后跑。",
                ],
                "use_when": "想用 GUI 一条龙生成 HOLE 曲线。",
                "inputs": ["WT + 突变体 PDB", "HOLE 轴参数（cpoint/cvect 等）"],
                "actions": ["准备 HOLE PDB", "执行 HOLE 管道"],
                "outputs": [
                    "每个模型一个 <model>-HOLE 子目录",
                    "*_hole.inp / *_hole.log / *_hole_profile.pdb / *_hole_spheres.pdb",
                ],
                "insights": "inp 的路径会被自动转成 /mnt/...，方便 WSL 执行。",
            },
            {
                "id": "hole_manual_mode",
                "title": "不想让 GUI 跑 HOLE？走“手动模式”也行",
                "tldr": "GUI 只负责生成 inp + 组织文件；你也可以自己在 WSL 跑脚本，最后再让 GUI 解析 log。",
                "steps": [
                    "在 GUI 取消勾选“自动在 WSL 中调用 HOLE”，先生成 *_hole.inp。",
                    "去 WSL 里按操作文档跑 run_hole.sh（一次跑 WT/DMI/DMT/GT/ND 并汇总最小半径行）。",
                    "跑完把 log 留在原目录，再回 GUI 勾“解析 log 生成 CSV&曲线”。",
                ],
                "use_when": "想在 WSL 里手动控制 HOLE 执行。",
                "inputs": ["*_hole.inp 文件", "WSL 可用 HOLE 命令"],
                "actions": ["手动运行 run_hole.sh", "回 GUI 解析 log"],
                "outputs": ["log 保留后可生成 CSV/曲线"],
                "insights": "手动模式更便于排查 HOLE 运行细节。",
            },
        ],
    },
    {
        "id": "msa_pipeline",
        "title": "MSA 自动候选｜从 FASTA 到候选表",
        "items": [
            {
                "id": "msa_auto_flow",
                "title": "一键 MSA + 自动候选到底做了啥",
                "tldr": "它先在 WSL 跑 clustalo 生成 *_msa.aln，再在 Windows 侧把 aln 拆成两个表：一个“可视化对齐表”，一个“候选位点表”。",
                "steps": [
                    "准备一个多序列 FASTA（放在普通路径文件夹，别放桌面奇怪路径）。",
                    "在 GUI 的 “MSA 自动候选小工具” 选择 FASTA，点 “一键跑 MSA + 自动候选”。",
                    "用 Excel 打开 candidate_sites_auto_v0.1.csv，挑你想验证的位点，再整理进你自己的候选表。",
                ],
                "use_when": "想从 FASTA 直接生成候选位点表。",
                "inputs": ["多序列 FASTA"],
                "actions": ["一键跑 MSA + 自动候选"],
                "outputs": [
                    "<stem>_msa.aln（clustalo 输出）",
                    "alignment_view.csv（对齐可视化）",
                    "candidate_sites_auto_v0.1.csv（候选位点表）",
                ],
                "insights": "候选表适合初筛，再结合结构/功能做二次筛选。",
            },
        ],
    },
    {
        "id": "global_view",
        "title": "研究模式｜全景&ROI",
        "items": [
            {
                "id": "full_coulombic",
                "title": "1. FULL 静电势（全蛋白）",
                "tldr": "整蛋白表面电势对比，用来看整体电荷地形有没有被突变改写。",
                "steps": [
                    "勾选：FULL 静电势",
                    "需要：WT PDB + 突变体 PDB（可多条）",
                    "生成 .cxc → ChimeraX runscript",
                ],
                "use_when": "想看全局电荷格局有没有大改、远端是否被牵动。",
                "inputs": ["WT PDB（必填）", "突变体 PDB（可多模型）"],
                "actions": ["勾 FULL 静电势 → 生成 .cxc → ChimeraX runscript"],
                "outputs": ["out_dir/WT/WT_coulombic.png", "out_dir/<MUT>/<MUT>_coulombic.png"],
                "insights": "整体偏正/偏负/补丁位置，帮你判断是否有远程静电效应。",
            },
            {
                "id": "roi_contacts",
                "title": "5. ROI 局部接触图",
                "tldr": "指定 ROI，画 ≤4Å 接触的对比图，方便肉眼判读。",
                "steps": [
                    "填 ROI 残基表达式",
                    "勾 ROI 接触",
                    "生成 .cxc → ChimeraX runscript",
                ],
                "use_when": "要在特定片段一眼看“谁靠近/谁远离”。",
                "inputs": ["ROI 残基表达式", "链 ID（默认 A）"],
                "actions": ["研究模式 → 勾 ROI 接触 → 生成 .cxc"],
                "outputs": ["out_dir/gate_sites/<Model>_sites_contacts.png"],
                "insights": "用作 Contacts_Qualitative 的佐证；配合电势图更全面。",
                "pitfalls": ["ROI 填空=不会生成", "只生成 .cxc 不等于完成，记得去 ChimeraX 跑"]
            },
            {
                "id": "roi_coulombic",
                "title": "6. ROI 局部静电势图",
                "tldr": "ROI 电势补丁对比，解释局部微环境的倾向变化（别硬因果）。",
                "steps": [
                    "填 ROI 残基表达式",
                    "勾 ROI 静电势",
                    "生成 .cxc → ChimeraX runscript",
                ],
                "use_when": "想知道 ROI 附近的正/负势补丁有没有翻转或强化。",
                "inputs": ["ROI 残基表达式", "链 ID（默认 A）"],
                "actions": ["研究模式 → 勾 ROI 静电势 → 生成 .cxc"],
                "outputs": ["out_dir/gate_sites/<Model>_sites_coulombic.png"],
                "insights": "把“电势更正/更负”的观察写进 stage3 表的 Patch_Electrostatics。",
            },
        ],
    },
    {
        "id": "gate_analysis",
        "title": "门闩分析（接触/氢键/SASA）",
        "items": [
            {
                "id": "contacts_near",
                "title": "2. 近景接触（≤4Å）",
                "tldr": "以目标残基为中心的接触网络，看看门闩是否更挤或更松。",
                "steps": [
                    "填：目标残基表达式",
                    "勾 近景接触",
                    "生成 .cxc → ChimeraX runscript",
                ],
                "use_when": "关心门闩附近的堆叠/释放趋势。",
                "inputs": ["目标残基表达式（如 298-300）", "链 ID"],
                "actions": ["研究模式 → 勾 近景接触 → 生成 .cxc"],
                "outputs": ["out_dir/<Model>/<Model>_contacts.png"],
                "insights": "谁靠近/谁退场能解释封闭/松动；对照 ROI 图更稳。",
            },
            {
                "id": "hbonds_local",
                "title": "3. 近景氢键 + 日志",
                "tldr": "氢键数量和对象的变化，直接告诉你“门被谁拽着”。",
                "steps": [
                    "填：目标残基表达式",
                    "勾 近景氢键",
                    "生成 .cxc → ChimeraX runscript",
                ],
                "use_when": "需要可统计的氢键信息（后续汇总会读取 txt）。",
                "inputs": ["目标残基表达式", "链 ID", "输出等级建议 Standard 以上保留图片"],
                "actions": ["研究模式 → 勾 近景氢键 → 生成 .cxc"],
                "outputs": ["out_dir/<Model>/<Model>_hbonds.txt", "out_dir/<Model>/<Model>_hbonds.png（Standard/Full）"],
                "insights": "*_hbonds.txt 会被汇总用来计数，别删。图可肉眼检查氢键几何。",
                "pitfalls": ["Minimal 输出等级不会保存氢键图，只保留 txt"]
            },
            {
                "id": "sasa_targets",
                "title": "4. 目标残基 SASA",
                "tldr": "给目标残基算暴露度，结合接触/氢键解释微环境变化。",
                "steps": [
                    "填：目标残基表达式",
                    "勾 目标残基 SASA",
                    "生成 .cxc → ChimeraX runscript",
                ],
                "use_when": "想要可量化的埋藏/暴露度（后续 metrics 会用）。",
                "inputs": ["目标残基表达式", "链 ID"],
                "actions": ["研究模式 → 勾 SASA → 生成 .cxc"],
                "outputs": ["out_dir/<Model>/<Model>_sasa.html"],
                "insights": "SASA 数字 + 氢键/接触组合，能解释为什么环境变了。",
            },
        ],
    },
    {
        "id": "hole_pipeline",
        "title": "HOLE 管道",
        "items": [
            {
                "id": "hole_prepare",
                "title": "HOLE 输入准备",
                "tldr": "把 WT/突变体 PDB 和轴参数准备好，生成每个模型的 HOLE 输入。",
                "steps": [
                    "填 HOLE 目录 + 模型列表（WT,DMI…）",
                    "生成找轴 .cxc → 在 ChimeraX 跑 → 回填 cpoint/cvect",
                    "点“从 WT+突变体准备 HOLE PDB”",
                ],
                "use_when": "正式跑 HOLE 之前的准备阶段。",
                "inputs": ["HOLE 工作目录", "模型列表（逗号分隔）", "链 ID", "找轴残基表达式/或手填 cpoint,cvect"],
                "actions": ["生成找轴 .cxc → ChimeraX → 回填轴参数", "从 WT+突变体准备 HOLE PDB"],
                "outputs": ["<HOLE目录>/<Model>.pdb", "<Model>_hole.inp"],
                "insights": "轴参数正确与否直接影响曲线可信度，建议用自动找轴。",
            },
            {
                "id": "hole_run",
                "title": "执行 HOLE + 汇总",
                "tldr": "一键跑 HOLE（可自动调用 WSL），并生成曲线/摘要。",
                "steps": [
                    "勾“自动在 WSL 调用 HOLE”可直接跑；否则手动跑 log",
                    "勾“根据 log 生成 CSV & 曲线图”",
                    "点“执行 HOLE 管道”",
                ],
                "use_when": "准备好 inp/pdb 后正式出孔径曲线。",
                "inputs": ["HOLE 工作目录（包含 *_hole.inp）", "WSL conda 配置或自定义 HOLE 命令"],
                "actions": ["执行 HOLE 管道"],
                "outputs": [
                    "<HOLE目录>/<Model>-HOLE/<Model>_hole.log",
                    "<HOLE目录>/<Model>-HOLE/<Model>_hole_profile.pdb",
                    "hole_profile_samples.csv",
                    "hole_min_table.csv",
                    "hole_min_summary.csv",
                    "hole_profiles.png",
                ],
                "insights": "重点看 r_min_A 和 gate_length_A，越小/越长代表越卡。",
                "pitfalls": ["WSL 路径/conda 环境不对会导致 HOLE 失败"]
            },
        ],
    },
    {
        "id": "summary_metrics",
        "title": "汇总&评分（metrics / stage3）",
        "items": [
            {
                "id": "summaries",
                "title": "汇总 SASA + 氢键",
                "tldr": "把 *_sasa.html 和 *_hbonds.txt 变成可统计的表。",
                "steps": [
                    "填研究输出目录 out_dir",
                    "点“汇总 SASA / H-bonds”",
                    "查看 out_dir/tables/ 下的 CSV",
                ],
                "use_when": "ChimeraX 跑完研究模式后想做量化。",
                "inputs": ["研究模式输出目录 out_dir"],
                "actions": ["汇总 SASA / H-bonds"],
                "outputs": ["tables/sasa_hbonds_summary.csv", "tables/sasa_per_residue.csv"],
                "insights": "这是后续打分的基础表，别遗漏 hbonds.txt / sasa.html。",
            },
            {
                "id": "metrics_merge",
                "title": "合并 HOLE + SASA 指标",
                "tldr": "把 HOLE 的 r_min/gate_length 与 SASA/H-bonds 汇成一张 metrics 表并评分。",
                "steps": [
                    "填 hole_dir + sasa_dir",
                    "点“合并 HOLE + SASA 指标”",
                    "可选：上传标准集做线性拟合评分",
                ],
                "use_when": "有 HOLE 结果后需要一个综合指标。",
                "inputs": ["hole_dir（含 hole_min_table.csv）", "sasa_dir（含 tables/sasa_hbonds_summary.csv）"],
                "actions": ["合并 HOLE + SASA 指标", "可选：评分 metrics 文件"],
                "outputs": ["tables/metrics_all.csv", "tables/metrics_scored.csv"],
                "insights": "GateTightScore + HydroScore 组合的 TotalScore 只代表结构指标，仍需实验验证。",
            },
            {
                "id": "stage3_table",
                "title": "生成决策表 stage3_table.csv",
                "tldr": "自动列好图片路径和量化指标，留空列给你填主观判读。",
                "steps": [
                    "汇总完指标后点击“生成 stage3 表”",
                    "打开 tables/stage3_table.csv",
                    "手填 Patch_Electrostatics / Contacts_Qualitative",
                ],
                "use_when": "要做最终决策/汇报，需把证据链整理成表。",
                "inputs": ["研究输出目录 out_dir"],
                "actions": ["生成决策表模板（stage3_table.csv）"],
                "outputs": ["tables/stage3_table.csv"],
                "insights": "表里会带上 ROI 接触/电势图路径，直接拷进幻灯或报告。",
            },
        ],
    },
    {
        "id": "faq",
        "title": "常见报错",
        "items": [
            {
                "id": "swapaa",
                "title": "swapaa 找不到残基/链",
                "tldr": "99% 是链 ID 或编号对不上。",
                "steps": [
                    "在 ChimeraX 试 select #1/A:298 是否选中",
                    "确认 GUI 里链 ID/编号一致",
                    "重跑生成 .cxc",
                ],
                "use_when": "ChimeraX 报 swapaa 找不到残基/链。",
                "inputs": ["正确的链 ID", "与 PDB 匹配的残基编号"],
                "actions": ["在 ChimeraX 手动 select 验证", "改正链/编号后重新生成脚本"],
                "outputs": ["无新输出（解决后再跑正常产出）"],
                "insights": "先在 ChimeraX 验证选择是否命中，能提前排坑。",
            },
            {
                "id": "no_outputs",
                "title": "ChimeraX 跑完没输出图",
                "tldr": "多半是路径/权限问题，或只生成了 .cxc 没跑。",
                "steps": [
                    "确认 out_dir 有写权限，路径别含奇怪符号",
                    "确保在 ChimeraX 真正 runscript 过",
                    "再看输出目录是否有文件",
                ],
                "use_when": "生成 .cxc 成功，但目录里空空。",
                "inputs": ["有效的 out_dir 路径"],
                "actions": ["检查路径权限", "重新 runscript"],
                "outputs": ["正常情况下应生成对应 PNG/HTML/TXT"] ,
                "insights": "Windows 路径会自动转成 /，尽量避免奇怪符号。",
            },
            {
                "id": "summary_missing",
                "title": "汇总时报：找不到 *_sasa.html 或 *_hbonds.txt",
                "tldr": "要么没跑相关步骤，要么忘了 runscript。",
                "steps": [
                    "确认勾选了 SASA/氢键并在 ChimeraX 跑过",
                    "检查 out_dir 是否有对应 html/txt",
                    "缺啥补跑啥，再点汇总",
                ],
                "use_when": "汇总时报缺文件。",
                "inputs": ["完整的研究模式输出目录"],
                "actions": ["补跑缺失的步骤", "重新汇总"],
                "outputs": ["缺失文件补齐后可生成汇总 CSV"],
                "insights": "只跑 ROI（5/6）不会有 SASA/氢键文件，正常现象。",
            },
            {
                "id": "hole_fail",
                "title": "HOLE 自动运行失败",
                "tldr": "先排查 WSL 可执行和 conda 环境。",
                "steps": [
                    "在 WSL 手动跑 hole 看是否可用",
                    "核对 PP.py 里的 HOLE_WSL_CONDA_INIT/ENV",
                    "必要时改“HOLE 命令”为完整可执行路径",
                ],
                "use_when": "执行 HOLE 管道报错。",
                "inputs": ["正确的 WSL 环境配置"],
                "actions": ["WSL 手测 HOLE", "修正 conda 路径或命令"],
                "outputs": ["修复后再跑可得到 log/曲线"],
                "insights": "先确保命令在 WSL 单独可跑，再交给 GUI。",
            },
            {
                "id": "msa_fail",
                "title": "MSA 失败：找不到 Clustal-Omega",
                "tldr": "检查 clustalo 路径（默认 /usr/bin/clustalo）。",
                "steps": [
                    "在 WSL 里执行 which clustalo",
                    "如路径不同，在 PP.py 配置 CLUSTALO_WSL_EXE",
                    "重跑“一键跑 MSA”",
                ],
                "use_when": "MSA 模块报找不到 clustalo。",
                "inputs": ["正确的 clustalo 路径"],
                "actions": ["更新配置", "重新运行 MSA"],
                "outputs": ["<stem>_msa.aln", "alignment_view.csv", "candidate_sites_auto_v0.1.csv"],
                "insights": "路径配好一次即可复用。",
            },
        ],
    },
]
